services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:latest
    # bound trough ViaProxy
    #ports:
    #  - 25565:25565
    environment:
      EULA: "TRUE"
      USE_MEOWICE_FLAGS: true

      MOTD: |
        §r§c§lN§9§lO§a§lT§rmc§r
        🌊 Liity versiolla %VERSION% tai päälle
      ICON: /icon.png
      OVERRIDE_ICON: true
  
      DIFFICULTY: hard
      OPS: koodarimpi
      ONLINE_MODE: false
      SERVER_NAME: NOTmc

    volumes:
      - ./icon.png:/icon.png
      - mc-data:/data
  viaproxy:
    container_name: viaproxy
    image: ghcr.io/viaversion/viaproxy:main
    volumes:
      - ./viaproxy:/app/run
    ports:
      - 25565:25565
    depends_on:
      - minecraft
  phantom:
    container_name: phantom
    build:
      context: .
      dockerfile: phantom.containerfile
      args:
        - PHANTOM_VERSION=v0.5.4
    ports:
      - 19133:19133
      - 19132:19232
    environment:
      PHANTOM_UPSTREAM_ADDRESS: viaproxy:25565
      PHANTOM_PORT: 19133
    depends_on:
     - viaproxy
volumes:
  mc-data:
